// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbaHnDuXxyfowHTBV-61WYS0WB8L7KRkM',
    appId: '1:177604934389:web:6c9c6ee339244f7b4763bc',
    messagingSenderId: '177604934389',
    projectId: 'todolist-55d42',
    authDomain: 'todolist-55d42.firebaseapp.com',
    storageBucket: 'todolist-55d42.firebasestorage.app',
    measurementId: 'G-LT8NS82E6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGxKFxQQAyxmZiHYKFevoeDToSq-byjk',
    appId: '1:177604934389:android:9544858129fd73324763bc',
    messagingSenderId: '177604934389',
    projectId: 'todolist-55d42',
    storageBucket: 'todolist-55d42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0Cm_fFw4fOuBOOZ4qbFeBo2ffYjWWfM',
    appId: '1:177604934389:ios:3c8ae1eebeb7c48e4763bc',
    messagingSenderId: '177604934389',
    projectId: 'todolist-55d42',
    storageBucket: 'todolist-55d42.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo0Cm_fFw4fOuBOOZ4qbFeBo2ffYjWWfM',
    appId: '1:177604934389:ios:3c8ae1eebeb7c48e4763bc',
    messagingSenderId: '177604934389',
    projectId: 'todolist-55d42',
    storageBucket: 'todolist-55d42.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbaHnDuXxyfowHTBV-61WYS0WB8L7KRkM',
    appId: '1:177604934389:web:ce190de5a2b40f524763bc',
    messagingSenderId: '177604934389',
    projectId: 'todolist-55d42',
    authDomain: 'todolist-55d42.firebaseapp.com',
    storageBucket: 'todolist-55d42.firebasestorage.app',
    measurementId: 'G-JTVLZWY4C1',
  );
}
